version: CI {branch} Build {build}
image: Visual Studio 2019 Preview
configuration: Release
platform: Any CPU
environment:
 NUGET_DEPLOY_SECRET:
  secure: cM8uuOzvNOaDyTnb9fRQbRi5sm5Tc/NqcpvscOA798nT7qAS16nfxqFGHFNTr3EG
 
pull_requests:
  do_not_increment_build_number: true
init:
- ps: ''
install:
- ps: #nuget sources
- ps: #dotnet nuget --version
- ps: #appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
- ps: $env:PADDED_BUILD_NUMBER = ([int]$env:appveyor_build_number).ToString("00000")
nuget:
  disable_publish_on_pr: true
  disable_publish_octopus: true  
artifacts:
- path: '.\snupkg\**\*.snupkg'
  name: ReleaseSnu
- path: '.\snupkg\**\*.nupkg'
  name: ReleaseSnu
- path: '.\nupkg\**\*.nupkg'
  name: Release
      
deploy:
- provider: NuGet
  api_key:
    secure: cM8uuOzvNOaDyTnb9fRQbRi5sm5Tc/NqcpvscOA798nT7qAS16nfxqFGHFNTr3EG
  artifact: Release
after_deploy:
 - ps : Get-ChildItem .\snupkg\*.snupkg | % { dotnet nuget push $_.FullName -s https://api.nuget.org/v3/index.json -k $env:NUGET_DEPLOY_SECRET }
  
for:


-
  branches:
    only:
      - dev
  build_script:
    - cmd: dotnet pack -c Release --include-symbols -v m -o  .\nupkg\ .\src\Amusoft.UI.WPF\Amusoft.UI.WPF.csproj --version-suffix alpha%PADDED_BUILD_NUMBER% --include-source 
    - cmd: dotnet pack -c Release --include-symbols -v m -o .\snupkg\ .\src\Amusoft.UI.WPF\Amusoft.UI.WPF.csproj --version-suffix alpha%PADDED_BUILD_NUMBER% -p:SymbolPackageFormat=snupkg 

  
  
-
  branches:
    only:
      - release 
  build_script:
    - cmd: dotnet pack -c Release --include-symbols -v m -o  .\nupkg\ .\src\Amusoft.UI.WPF\Amusoft.UI.WPF.csproj --include-source 
    - cmd: dotnet pack -c Release --include-symbols -v m -o .\snupkg\ .\src\Amusoft.UI.WPF\Amusoft.UI.WPF.csproj -p:SymbolPackageFormat=snupkg 

  
  
  
-
  branches:
    only:
      - master 
  deploy: off
  artifacts: off
  build_script:
  - cmd: dotnet build -c Release .\src\Amusoft.UI.WPF\Amusoft.UI.WPF.csproj -v m
